name: deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create config file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG_JSON }}

      - name: Create database config file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "config_db.json"
          json: ${{ secrets.CONFIG_DB_JSON }}

      - name: Move database config file
        run: |
          mkdir -p config
          mv config_db.json config/config.json

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_NODE_ENV: production
          envkey_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          envkey_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          envkey_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          
      - name: Down the former version of the bot
        run: |
          sudo docker compose logs -t >> ~/logs/lollipop.log
          sudo docker compose down

      - name: Launch the bot
        run: |
          sudo docker compose build
          sudo docker compose up -d
